backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "scriptGroup"
    label: "Script Group"
    folder: "_groups"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "scriptGroup" }
      - { label: "Title", name: "title", widget: "string", required: true }
  - name: "scriptPage"
    label: "Script Page"
    folder: "_scripts"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "scriptPage" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Script Parent", name: "parent", widget: "relation", collection: "scriptGroup", search_fields: ["title"], value_field: "title", display_fields: ["title"], multiple: false }
      - label: "Script"
        name: "script"
        widget: "list"
        fields: 
          - { label: "Script Text", name: "text", widget: "markdown" }
          - { label: "Icon", name: "icon", widget: "image", required: false }
      - label: "Navigation"
        name: "navigation"
        widget: "list"
        required: false
        fields: 
          - { label: "Button Text", name: "text", widget: "string", required: true }
          - { label: "Button Colour", name: "color", widget: "select", options: ["Green","Red"] }
          - { label: "Is Disposition?", name: "disposition", widget: "boolean", default: false }
          - label: "Link to"
            name: "link"
            widget: "relation"
            collection: "scriptPage"
            search_fields: ["title","parent"]
            value_field: "{{slug}}"
            display_fields: ["title","parent"]
            multiple: false
            required: false
