backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads
collections:
  - name: "scriptGroup"
    label: "Script Group"
    folder: "_groups"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "scriptGroup" }
      - { label: "Title", name: "title", widget: "string", required: true }
  - name: "scriptPage"
    label: "Script Page"
    folder: "_scripts"
    create: true
    slug: "{{slug}}"
    summary: "{{ title }} - {{ parent }}"
    fields: 
      - { label: "Layout", name: "layout", widget: "hidden", default: "scriptPage" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Script Parent", name: "parent", widget: "relation", collection: "scriptGroup", search_fields: ["title"], value_field: "title", display_fields: ["title"], multiple: false }
      - { label: "Is Start Page?", name: "start", widget: "boolean", default: false } 
      - label: "Script"
        name: "script"
        widget: "list"
        fields: 
          - { label: "Script Text", name: "text", widget: "markdown" }
          - { label: "Alignment", name: "align", widget: "select", options: ["Left", "Center", "Right"], default: "Left" }
          - { label: "Icon", name: "icon", widget: "image", required: false }
      - label: "Navigation"
        name: "navigation"
        widget: "list"
        required: false
        fields: 
          - { label: "Button Text", name: "text", widget: "string", required: true }
          - { label: "Button Colour", name: "color", widget: "select", options: ["Green","Red"] }
          - { label: "Is Disposition?", name: "disposition", widget: "boolean", default: false }
          - label: "Link to"
            name: "link"
            widget: "relation"
            collection: "scriptPage"
            search_fields: ["title","parent"]
            value_field: "{{slug}}"
            display_fields: ["title","parent"]
            multiple: false
            required: false
